### ISSUE TITLE
is heb geen idee wat er met de css gebeurt

### ISSUE THREAD

**Issue by Vivaloz** [JelNet-webapplications/JelCraft-Homepage#105]
ok stel

je opent de website met op de pc versie
![image](https://user-images.githubusercontent.com/88946435/215270703-5d197fd7-0eb1-4b19-bd4d-9b4403cdfaf3.png)

dan maak je het tabblad kleiner (dan heb je de mobile versie dus)
![image](https://user-images.githubusercontent.com/88946435/215270670-10bf66b8-7d30-4340-9a5c-c2a2923301ff.png)

je ververst de pagina
![image](https://user-images.githubusercontent.com/88946435/215270677-5409afcb-4925-4678-a298-9e2a9b805f79.png)

er toch was de css van Projects verneukt en dat 7em gebeuren is er weer

wat

**Comment by JelCraft** [comment]
Werkt position: fixed nog wel na het refreshen?

(Dat de header dus altijd bovenaan blijft staan & niet mee scrollt)
