### ISSUE TITLE
internal/external zijn aparte bestanden

### ISSUE THREAD

**Issue by Vivaloz** [JelNet-webapplications/JelCraft-Homepage#115]
dat kan je centraliseren met php. Heb ik al vaker gedaan, is 1000 x handiger.

**Comment by JelCraft** [comment]
Ik heb werkelijkwaar geen idee hoe dit werkt, maar klinkt als een flinke verbetering, dan werk je zeker met die anchor tags (#), of niet?

**Comment by Vivaloz** [comment]
zou ik niet doen, dat maakt het alleen maar ingewikkelder
je kan html fragmenten opslaan als variabele in php zeg maar (zonder dat je dan dat json tering tyfus gebeuren krijgt)

**Comment by Vivaloz** [comment]
dan kan je op iedere pagina gewoon in de html zetten <?php load("dingetje") ?> en dan staat het daar
hetzelfde geldt voor de header
dan heb je één bestandje waar dat html fragment in staat en dan wordt iedere pagina op de website automatisch veranderd

**Comment by JelCraft** [comment]
Dat klinkt echt 100x beter, net zoals toen we de CSS allemaal gecentraliseerd hadden zodat het over alle pagina's gelijk is. Met de implementatie heb ik echter lichtelijk wat hulp nodig

**Comment by Vivaloz** [comment]
mijn leven heeft nut gekregen
