### ISSUE TITLE
het contactformulier heeft geen ip-tracker

### ISSUE THREAD

**Issue by Vivaloz** [JelNet-webapplications/JelCraft-Homepage#42]

**Comment by JelCraft** [comment]
dacht ik dat ik het eindelijk opgelost te hebben door alle server requests te cachen maar nee.. moet persé weer op het contactformulier natuurlijk.. 🙄

**Comment by Vivaloz** [comment]
ook goed, is enkel de verwoording hè

**Comment by Vivaloz** [comment]
t is gefikst?
