### ISSUE TITLE
er is nog geen duidelijke weergave van de voortgang van een project

### ISSUE THREAD

**Issue by Vivaloz** [JelNet-webapplications/JelCraft-Homepage#81]

**Comment by JelCraft** [comment]
Een progress balkje zou wel gaaf zijn, maar is natuurlijk wel lastig in te schatten dit. Misschien een tijdlijn van de laatste veranderingen/commits in de beschrijving? bvb:

### Dirk Map [NDY]
- [ 5/1 ] Rendering engine updated
- [ 7/1 ] UI Fix (Header)

**Comment by Vivaloz** [comment]
het idee was toch heel simpel? groen vierkantje als ie af is, oranje als ie wip is en rood als ie ndy is

**Comment by Vivaloz** [comment]
@JelCraft je moet er eens naar kijken

trouwens je kan ook klikken op "Progress" dan heb je pas echt de magie

**Comment by JelCraft** [comment]
dit is echt geweldig fancy wtf

**Comment by Vivaloz** [comment]
beetje scuffed op mobile maar op pc best cool

**Comment by Vivaloz** [comment]
mijn.
